name: "Prepare Wheel For Release"
description: "Build ttexalens wheel for release"

inputs:
  python-version:
    description: "Python version to use"
    required: true
  build-version:
    description: "Build version tag (e.g., 'latest', '1.0.0')"
    required: true
  os:
    description: "Operating system"
    required: false
    default: "ubuntu-22.04"
  docker-os:
    description: "Docker os"
    required: false
    default: "ubuntu-22-04"

outputs:
  wheel-name:
    description: "The name of the uploaded wheel artifact"
    value: ${{ steps.set-wheel-name.outputs.wheel-name }}

runs:
  using: "composite"
  steps:
    - name: "Build wheel"
      shell: bash
      run: |
        make wheel

      # Make wheel compatible with manylinux using auditwheel, PyPi requires manylinux compatibility
    - name: "Install auditwheel and repair wheel"
      shell: bash
      run: |
        pip install auditwheel
        mkdir -p build/ttexalens_wheel/repaired
        echo "Repairing wheel to make it manylinux compatible..."
        auditwheel repair build/ttexalens_wheel/tt_exalens*.whl -w build/ttexalens_wheel/repaired/ || {
          echo "auditwheel repair failed, wheel might already be manylinux compatible or repair not possible"
          cp build/ttexalens_wheel/tt_exalens*.whl build/ttexalens_wheel/repaired/
        }
        # Replace original wheel with repaired one
        rm -f build/ttexalens_wheel/tt_exalens*.whl
        mv build/ttexalens_wheel/repaired/*.whl build/ttexalens_wheel/
        rmdir build/ttexalens_wheel/repaired
        echo "Final wheel:"
        ls -lh build/ttexalens_wheel/

    - name: "Set wheel artifact name"
      id: set-wheel-name
      shell: bash
      run: |
        echo wheel_name="tt-exalens-v${{ inputs.build-version }}-${{ inputs.python-version }}-${{ inputs.os }}.whl" >> $GITHUB_OUTPUT

    - name: "Upload wheel as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-wheel-name.outputs.wheel-name }}
        path: build/ttexalens_wheel/*.whl
