name: "Prepare Wheel For Release"
description: "Build ttexalens wheel for release"

inputs:
  build-version:
    description: "Build version tag (e.g., 'latest', '1.0.0')"
    required: true
  ubuntu-version:
    description: "Ubuntu version (e.g., '22.04', '24.04') "
    required: false
    default: "22.04"

outputs:
  wheel-name:
    description: "The name of the uploaded wheel artifact"
    value: ${{ steps.set-wheel-name.outputs.wheel-name }}

runs:
  using: "composite"
  steps:
    - name: "ccache"
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: ttexalens-Release-ubuntu-${{ inputs.ubuntu-version }}

    - name: "Build wheel"
      shell: bash
      run: |
        make wheel

    - name: "Set wheel artifact name"
      id: set-wheel-name
      shell: bash
      run: |
        echo "wheel-name=tt-exalens-v${{ inputs.build-version }}-ubuntu-${{ inputs.ubuntu-version }}.whl" >> $GITHUB_OUTPUT

    - name: "Upload wheel as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-wheel-name.outputs.wheel-name }}
        path: build/ttexalens_wheel/*.whl
