name: "Prepare Wheel For Release"
description: "Build ttexalens wheel for release"

inputs:
  python-version:
    description: "Python version to use"
    required: true
  build-version:
    description: "Build version tag (e.g., 'latest', '1.0.0')"
    required: true
  os:
    description: "Operating system"
    required: false
    default: "ubuntu-22.04"

outputs:
  wheel-name:
    description: "The name of the uploaded wheel artifact"
    value: ${{ steps.set-wheel-name.outputs.wheel-name }}

runs:
  using: "composite"
  steps:
    - name: "Build wheel"
      shell: bash
      run: |
        make wheel
    - name: "Set wheel name"
      id: set-wheel-name
      shell: bash
      run: |
        echo "wheel-name=tt-exalens-v${{ inputs.build-version }}-${{ inputs.python-version }}-${{ inputs.os }}" >> $GITHUB_OUTPUT
    - name: "Upload wheel as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-wheel-name.outputs.wheel-name }}
        path: build/ttexalens_wheel/*.whl
