ARG UBUNTU_VERSION=22.04
FROM ubuntu:${UBUNTU_VERSION}
SHELL ["/bin/bash", "-c"]

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Copy the requirements files for pip in current directory
COPY ttexalens/requirements.txt \
    ttexalens/dev-requirements.txt \
    test/test_requirements.txt \
    .github/Dockerfile.ci.sh \
    ./

# Run single script to setup the environment in order to generate a single layer
RUN ./Dockerfile.ci.sh
