// SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <dwarf.h>
#include <libdwarf.h>

#include <cstdint>
#include <string>
#include <utility>
#include <variant>
#include <vector>

namespace ttexalens::native_elf {

// Attribute tags - DW_AT_*
enum class DwarfAttributeTag : Dwarf_Half {
    abstract_origin = DW_AT_abstract_origin,
    accessibility = DW_AT_accessibility,
    addr_base = DW_AT_addr_base,
    address_class = DW_AT_address_class,
    alignment = DW_AT_alignment,
    allocated = DW_AT_allocated,
    ALTIUM_loclist = DW_AT_ALTIUM_loclist,
    APPLE_block = DW_AT_APPLE_block,
    APPLE_flags = DW_AT_APPLE_flags,
    APPLE_isa = DW_AT_APPLE_isa,
    APPLE_major_runtime_vers = DW_AT_APPLE_major_runtime_vers,
    APPLE_objc_complete_type = DW_AT_APPLE_objc_complete_type,
    APPLE_objc_direct = DW_AT_APPLE_objc_direct,
    APPLE_omit_frame_ptr = DW_AT_APPLE_omit_frame_ptr,
    APPLE_optimized = DW_AT_APPLE_optimized,
    APPLE_origin = DW_AT_APPLE_origin,
    APPLE_property = DW_AT_APPLE_property,
    APPLE_property_attribute = DW_AT_APPLE_property_attribute,
    APPLE_property_getter = DW_AT_APPLE_property_getter,
    APPLE_property_name = DW_AT_APPLE_property_name,
    APPLE_property_setter = DW_AT_APPLE_property_setter,
    APPLE_runtime_class = DW_AT_APPLE_runtime_class,
    APPLE_sdk = DW_AT_APPLE_sdk,
    artificial = DW_AT_artificial,
    associated = DW_AT_associated,
    base_types = DW_AT_base_types,
    binary_scale = DW_AT_binary_scale,
    bit_offset = DW_AT_bit_offset,
    bit_size = DW_AT_bit_size,
    bit_stride = DW_AT_bit_stride,
    body_begin = DW_AT_body_begin,
    body_end = DW_AT_body_end,
    BORLAND_closure = DW_AT_BORLAND_closure,
    BORLAND_Delphi_ABI = DW_AT_BORLAND_Delphi_ABI,
    BORLAND_Delphi_anonymous_method = DW_AT_BORLAND_Delphi_anonymous_method,
    BORLAND_Delphi_class = DW_AT_BORLAND_Delphi_class,
    BORLAND_Delphi_constructor = DW_AT_BORLAND_Delphi_constructor,
    BORLAND_Delphi_destructor = DW_AT_BORLAND_Delphi_destructor,
    BORLAND_Delphi_frameptr = DW_AT_BORLAND_Delphi_frameptr,
    BORLAND_Delphi_interface = DW_AT_BORLAND_Delphi_interface,
    BORLAND_Delphi_metaclass = DW_AT_BORLAND_Delphi_metaclass,
    BORLAND_Delphi_record = DW_AT_BORLAND_Delphi_record,
    BORLAND_Delphi_unit = DW_AT_BORLAND_Delphi_unit,
    BORLAND_property_default = DW_AT_BORLAND_property_default,
    BORLAND_property_implements = DW_AT_BORLAND_property_implements,
    BORLAND_property_index = DW_AT_BORLAND_property_index,
    BORLAND_property_read = DW_AT_BORLAND_property_read,
    BORLAND_property_write = DW_AT_BORLAND_property_write,
    byte_size = DW_AT_byte_size,
    byte_stride = DW_AT_byte_stride,
    call_all_calls = DW_AT_call_all_calls,
    call_all_source_calls = DW_AT_call_all_source_calls,
    call_all_tail_calls = DW_AT_call_all_tail_calls,
    call_column = DW_AT_call_column,
    call_data_location = DW_AT_call_data_location,
    call_data_value = DW_AT_call_data_value,
    call_file = DW_AT_call_file,
    call_line = DW_AT_call_line,
    call_origin = DW_AT_call_origin,
    call_parameter = DW_AT_call_parameter,
    call_pc = DW_AT_call_pc,
    call_return_pc = DW_AT_call_return_pc,
    call_tail_call = DW_AT_call_tail_call,
    call_target = DW_AT_call_target,
    call_target_clobbered = DW_AT_call_target_clobbered,
    call_value = DW_AT_call_value,
    calling_convention = DW_AT_calling_convention,
    common_reference = DW_AT_common_reference,
    comp_dir = DW_AT_comp_dir,
    const_expr = DW_AT_const_expr,
    const_value = DW_AT_const_value,
    containing_type = DW_AT_containing_type,
    count = DW_AT_count,
    CPQ_discontig_ranges = DW_AT_CPQ_discontig_ranges,
    CPQ_prologue_length = DW_AT_CPQ_prologue_length,
    CPQ_semantic_events = DW_AT_CPQ_semantic_events,
    CPQ_split_lifetimes_rtn = DW_AT_CPQ_split_lifetimes_rtn,
    CPQ_split_lifetimes_var = DW_AT_CPQ_split_lifetimes_var,
    data_bit_offset = DW_AT_data_bit_offset,
    data_location = DW_AT_data_location,
    data_member_location = DW_AT_data_member_location,
    decimal_scale = DW_AT_decimal_scale,
    decimal_sign = DW_AT_decimal_sign,
    decl_column = DW_AT_decl_column,
    decl_file = DW_AT_decl_file,
    decl_line = DW_AT_decl_line,
    declaration = DW_AT_declaration,
    default_value = DW_AT_default_value,
    defaulted = DW_AT_defaulted,
    deleted = DW_AT_deleted,
    description = DW_AT_description,
    digit_count = DW_AT_digit_count,
    discr = DW_AT_discr,
    discr_list = DW_AT_discr_list,
    discr_value = DW_AT_discr_value,
    dwo_id = DW_AT_dwo_id,
    dwo_name = DW_AT_dwo_name,
    element_list = DW_AT_element_list,
    elemental = DW_AT_elemental,
    encoding = DW_AT_encoding,
    endianity = DW_AT_endianity,
    entry_pc = DW_AT_entry_pc,
    enum_class = DW_AT_enum_class,
    explicit_ = DW_AT_explicit,
    export_symbols = DW_AT_export_symbols,
    extension = DW_AT_extension,
    external = DW_AT_external,
    frame_base = DW_AT_frame_base,
    friend_ = DW_AT_friend,
    ghs_frames = DW_AT_ghs_frames,
    ghs_frsm = DW_AT_ghs_frsm,
    ghs_lbrace_line = DW_AT_ghs_lbrace_line,
    ghs_mangled = DW_AT_ghs_mangled,
    ghs_namespace_alias = DW_AT_ghs_namespace_alias,
    ghs_rsm = DW_AT_ghs_rsm,
    ghs_rso = DW_AT_ghs_rso,
    ghs_subcpu = DW_AT_ghs_subcpu,
    ghs_using_declaration = DW_AT_ghs_using_declaration,
    ghs_using_namespace = DW_AT_ghs_using_namespace,
    GNAT_descriptive_type = DW_AT_GNAT_descriptive_type,
    GNU_addr_base = DW_AT_GNU_addr_base,
    GNU_all_call_sites = DW_AT_GNU_all_call_sites,
    GNU_all_source_call_sites = DW_AT_GNU_all_source_call_sites,
    GNU_all_tail_call_sites = DW_AT_GNU_all_tail_call_sites,
    GNU_bias = DW_AT_GNU_bias,
    GNU_call_site_data_value = DW_AT_GNU_call_site_data_value,
    GNU_call_site_target = DW_AT_GNU_call_site_target,
    GNU_call_site_target_clobbered = DW_AT_GNU_call_site_target_clobbered,
    GNU_call_site_value = DW_AT_GNU_call_site_value,
    GNU_deleted = DW_AT_GNU_deleted,
    GNU_denominator = DW_AT_GNU_denominator,
    GNU_discriminator = DW_AT_GNU_discriminator,
    GNU_dwo_id = DW_AT_GNU_dwo_id,
    GNU_dwo_name = DW_AT_GNU_dwo_name,
    GNU_entry_view = DW_AT_GNU_entry_view,
    GNU_exclusive_locks_required = DW_AT_GNU_exclusive_locks_required,
    GNU_guarded = DW_AT_GNU_guarded,
    GNU_guarded_by = DW_AT_GNU_guarded_by,
    GNU_locks_excluded = DW_AT_GNU_locks_excluded,
    GNU_locviews = DW_AT_GNU_locviews,
    GNU_macros = DW_AT_GNU_macros,
    GNU_numerator = DW_AT_GNU_numerator,
    GNU_odr_signature = DW_AT_GNU_odr_signature,
    GNU_pt_guarded = DW_AT_GNU_pt_guarded,
    GNU_pt_guarded_by = DW_AT_GNU_pt_guarded_by,
    GNU_pubnames = DW_AT_GNU_pubnames,
    GNU_pubtypes = DW_AT_GNU_pubtypes,
    GNU_ranges_base = DW_AT_GNU_ranges_base,
    GNU_shared_locks_required = DW_AT_GNU_shared_locks_required,
    GNU_tail_call = DW_AT_GNU_tail_call,
    GNU_template_name = DW_AT_GNU_template_name,
    GNU_vector = DW_AT_GNU_vector,
    go_closure_offset = DW_AT_go_closure_offset,
    go_dict_index = DW_AT_go_dict_index,
    go_elem = DW_AT_go_elem,
    go_embedded_field = DW_AT_go_embedded_field,
    go_key = DW_AT_go_key,
    go_kind = DW_AT_go_kind,
    go_package_name = DW_AT_go_package_name,
    go_runtime_type = DW_AT_go_runtime_type,
    high_pc = DW_AT_high_pc,
    HP_actuals_stmt_list = DW_AT_HP_actuals_stmt_list,
    HP_all_variables_modifiable = DW_AT_HP_all_variables_modifiable,
    HP_block_index = DW_AT_HP_block_index,
    HP_cold_region_high_pc = DW_AT_HP_cold_region_high_pc,
    HP_cold_region_low_pc = DW_AT_HP_cold_region_low_pc,
    HP_default_location = DW_AT_HP_default_location,
    HP_definition_points = DW_AT_HP_definition_points,
    HP_epilogue = DW_AT_HP_epilogue,
    HP_is_result_param = DW_AT_HP_is_result_param,
    HP_linkage_name = DW_AT_HP_linkage_name,
    HP_opt_flags = DW_AT_HP_opt_flags,
    HP_opt_level = DW_AT_HP_opt_level,
    HP_pass_by_reference = DW_AT_HP_pass_by_reference,
    HP_proc_per_section = DW_AT_HP_proc_per_section,
    HP_prof_flags = DW_AT_HP_prof_flags,
    HP_prof_version_id = DW_AT_HP_prof_version_id,
    HP_prologue = DW_AT_HP_prologue,
    HP_raw_data_ptr = DW_AT_HP_raw_data_ptr,
    HP_unit_name = DW_AT_HP_unit_name,
    HP_unit_size = DW_AT_HP_unit_size,
    HP_unmodifiable = DW_AT_HP_unmodifiable,
    HP_widened_byte_size = DW_AT_HP_widened_byte_size,
    IBM_alt_srcview = DW_AT_IBM_alt_srcview,
    IBM_home_location = DW_AT_IBM_home_location,
    IBM_wsa_addr = DW_AT_IBM_wsa_addr,
    identifier_case = DW_AT_identifier_case,
    import = DW_AT_import,
    inline_ = DW_AT_inline,
    INTEL_other_endian = DW_AT_INTEL_other_endian,
    is_optional = DW_AT_is_optional,
    language = DW_AT_language,
    language_name = DW_AT_language_name,
    language_version = DW_AT_language_version,
    linkage_name = DW_AT_linkage_name,
    LLVM_active_lane = DW_AT_LLVM_active_lane,
    LLVM_apinotes = DW_AT_LLVM_apinotes,
    LLVM_augmentation = DW_AT_LLVM_augmentation,
    LLVM_config_macros = DW_AT_LLVM_config_macros,
    LLVM_include_path = DW_AT_LLVM_include_path,
    LLVM_lane_pc = DW_AT_LLVM_lane_pc,
    LLVM_lanes = DW_AT_LLVM_lanes,
    LLVM_sysroot = DW_AT_LLVM_sysroot,
    LLVM_tag_offset = DW_AT_LLVM_tag_offset,
    LLVM_vector_size = DW_AT_LLVM_vector_size,
    location = DW_AT_location,
    loclists_base = DW_AT_loclists_base,
    low_pc = DW_AT_low_pc,
    lower_bound = DW_AT_lower_bound,
    mac_info = DW_AT_mac_info,
    macro_info = DW_AT_macro_info,
    macros = DW_AT_macros,
    main_subprogram = DW_AT_main_subprogram,
    member = DW_AT_member,
    MIPS_abstract_name = DW_AT_MIPS_abstract_name,
    MIPS_allocatable_dopetype = DW_AT_MIPS_allocatable_dopetype,
    MIPS_assumed_shape_dopetype = DW_AT_MIPS_assumed_shape_dopetype,
    MIPS_assumed_size = DW_AT_MIPS_assumed_size,
    MIPS_clone_origin = DW_AT_MIPS_clone_origin,
    MIPS_epilog_begin = DW_AT_MIPS_epilog_begin,
    MIPS_fde = DW_AT_MIPS_fde,
    MIPS_has_inlines = DW_AT_MIPS_has_inlines,
    MIPS_linkage_name = DW_AT_MIPS_linkage_name,
    MIPS_loop_begin = DW_AT_MIPS_loop_begin,
    MIPS_loop_unroll_factor = DW_AT_MIPS_loop_unroll_factor,
    MIPS_ptr_dopetype = DW_AT_MIPS_ptr_dopetype,
    MIPS_software_pipeline_depth = DW_AT_MIPS_software_pipeline_depth,
    MIPS_stride = DW_AT_MIPS_stride,
    MIPS_stride_byte = DW_AT_MIPS_stride_byte,
    MIPS_stride_elem = DW_AT_MIPS_stride_elem,
    MIPS_tail_loop_begin = DW_AT_MIPS_tail_loop_begin,
    mutable_ = DW_AT_mutable,
    name = DW_AT_name,
    namelist_item = DW_AT_namelist_item,
    noreturn = DW_AT_noreturn,
    object_pointer = DW_AT_object_pointer,
    ordering = DW_AT_ordering,
    PGI_lbase = DW_AT_PGI_lbase,
    PGI_lstride = DW_AT_PGI_lstride,
    PGI_soffset = DW_AT_PGI_soffset,
    picture_string = DW_AT_picture_string,
    priority = DW_AT_priority,
    producer = DW_AT_producer,
    prototyped = DW_AT_prototyped,
    pure = DW_AT_pure,
    ranges = DW_AT_ranges,
    rank = DW_AT_rank,
    recursive = DW_AT_recursive,
    reference = DW_AT_reference,
    return_addr = DW_AT_return_addr,
    rnglists_base = DW_AT_rnglists_base,
    rvalue_reference = DW_AT_rvalue_reference,
    segment = DW_AT_segment,
    sf_names = DW_AT_sf_names,
    sibling = DW_AT_sibling,
    signature = DW_AT_signature,
    small = DW_AT_small,
    specification = DW_AT_specification,
    src_coords = DW_AT_src_coords,
    src_info = DW_AT_src_info,
    start_scope = DW_AT_start_scope,
    static_link = DW_AT_static_link,
    stmt_list = DW_AT_stmt_list,
    str_offsets_base = DW_AT_str_offsets_base,
    stride = DW_AT_stride,
    stride_size = DW_AT_stride_size,
    string_length = DW_AT_string_length,
    string_length_bit_size = DW_AT_string_length_bit_size,
    string_length_byte_size = DW_AT_string_length_byte_size,
    SUN_alignment = DW_AT_SUN_alignment,
    SUN_amd64_parmdump = DW_AT_SUN_amd64_parmdump,
    SUN_browser_file = DW_AT_SUN_browser_file,
    SUN_c_vla = DW_AT_SUN_c_vla,
    SUN_cf_kind = DW_AT_SUN_cf_kind,
    SUN_command_line = DW_AT_SUN_command_line,
    SUN_compile_options = DW_AT_SUN_compile_options,
    SUN_count_guarantee = DW_AT_SUN_count_guarantee,
    SUN_dtor_length = DW_AT_SUN_dtor_length,
    SUN_dtor_start = DW_AT_SUN_dtor_start,
    SUN_dtor_state_deltas = DW_AT_SUN_dtor_state_deltas,
    SUN_dtor_state_final = DW_AT_SUN_dtor_state_final,
    SUN_dtor_state_initial = DW_AT_SUN_dtor_state_initial,
    SUN_f90_allocatable = DW_AT_SUN_f90_allocatable,
    SUN_f90_assumed_shape_array = DW_AT_SUN_f90_assumed_shape_array,
    SUN_f90_pointer = DW_AT_SUN_f90_pointer,
    SUN_f90_use_only = DW_AT_SUN_f90_use_only,
    SUN_fortran_based = DW_AT_SUN_fortran_based,
    SUN_fortran_main_alias = DW_AT_SUN_fortran_main_alias,
    SUN_func_offset = DW_AT_SUN_func_offset,
    SUN_func_offsets = DW_AT_SUN_func_offsets,
    SUN_hwcprof_signature = DW_AT_SUN_hwcprof_signature,
    SUN_import_by_lname = DW_AT_SUN_import_by_lname,
    SUN_import_by_name = DW_AT_SUN_import_by_name,
    SUN_is_omp_child_func = DW_AT_SUN_is_omp_child_func,
    SUN_language = DW_AT_SUN_language,
    SUN_link_name = DW_AT_SUN_link_name,
    SUN_memop_signature = DW_AT_SUN_memop_signature,
    SUN_memop_type_ref = DW_AT_SUN_memop_type_ref,
    SUN_namelist_spec = DW_AT_SUN_namelist_spec,
    SUN_obj_dir = DW_AT_SUN_obj_dir,
    SUN_obj_file = DW_AT_SUN_obj_file,
    SUN_omp_child_func = DW_AT_SUN_omp_child_func,
    SUN_omp_tpriv_addr = DW_AT_SUN_omp_tpriv_addr,
    SUN_original_name = DW_AT_SUN_original_name,
    SUN_part_link_name = DW_AT_SUN_part_link_name,
    SUN_pass_by_ref = DW_AT_SUN_pass_by_ref,
    SUN_pass_with_const = DW_AT_SUN_pass_with_const,
    SUN_profile_id = DW_AT_SUN_profile_id,
    SUN_return_value_ptr = DW_AT_SUN_return_value_ptr,
    SUN_return_with_const = DW_AT_SUN_return_with_const,
    SUN_template = DW_AT_SUN_template,
    SUN_vbase = DW_AT_SUN_vbase,
    SUN_vtable = DW_AT_SUN_vtable,
    SUN_vtable_abi = DW_AT_SUN_vtable_abi,
    SUN_vtable_index = DW_AT_SUN_vtable_index,
    threads_scaled = DW_AT_threads_scaled,
    TI_asm = DW_AT_TI_asm,
    TI_interrupt = DW_AT_TI_interrupt,
    TI_skeletal = DW_AT_TI_skeletal,
    TI_symbol_name = DW_AT_TI_symbol_name,
    TI_veneer = DW_AT_TI_veneer,
    TI_version = DW_AT_TI_version,
    trampoline = DW_AT_trampoline,
    type = DW_AT_type,
    upc_threads_scaled = DW_AT_upc_threads_scaled,
    upper_bound = DW_AT_upper_bound,
    use_GNAT_descriptive_type = DW_AT_use_GNAT_descriptive_type,
    use_location = DW_AT_use_location,
    use_UTF8 = DW_AT_use_UTF8,
    variable_parameter = DW_AT_variable_parameter,
    virtuality = DW_AT_virtuality,
    visibility = DW_AT_visibility,
    VMS_rtnbeg_pd_address = DW_AT_VMS_rtnbeg_pd_address,
    vtable_elem_location = DW_AT_vtable_elem_location,
};

// Attribute forms - DW_FORM_*
enum class DwarfAttributeForm : Dwarf_Half {
    addr = DW_FORM_addr,
    addrx = DW_FORM_addrx,
    addrx1 = DW_FORM_addrx1,
    addrx2 = DW_FORM_addrx2,
    addrx3 = DW_FORM_addrx3,
    addrx4 = DW_FORM_addrx4,
    block = DW_FORM_block,
    block1 = DW_FORM_block1,
    block2 = DW_FORM_block2,
    block4 = DW_FORM_block4,
    data1 = DW_FORM_data1,
    data16 = DW_FORM_data16,
    data2 = DW_FORM_data2,
    data4 = DW_FORM_data4,
    data8 = DW_FORM_data8,
    exprloc = DW_FORM_exprloc,
    flag = DW_FORM_flag,
    flag_present = DW_FORM_flag_present,
    GNU_addr_index = DW_FORM_GNU_addr_index,
    GNU_ref_alt = DW_FORM_GNU_ref_alt,
    GNU_str_index = DW_FORM_GNU_str_index,
    GNU_strp_alt = DW_FORM_GNU_strp_alt,
    implicit_const = DW_FORM_implicit_const,
    indirect = DW_FORM_indirect,
    line_strp = DW_FORM_line_strp,
    LLVM_addrx_offset = DW_FORM_LLVM_addrx_offset,
    loclistx = DW_FORM_loclistx,
    ref1 = DW_FORM_ref1,
    ref2 = DW_FORM_ref2,
    ref4 = DW_FORM_ref4,
    ref8 = DW_FORM_ref8,
    ref_addr = DW_FORM_ref_addr,
    ref_sig8 = DW_FORM_ref_sig8,
    ref_sup4 = DW_FORM_ref_sup4,
    ref_sup8 = DW_FORM_ref_sup8,
    ref_udata = DW_FORM_ref_udata,
    rnglistx = DW_FORM_rnglistx,
    sdata = DW_FORM_sdata,
    sec_offset = DW_FORM_sec_offset,
    string = DW_FORM_string,
    strp = DW_FORM_strp,
    strp_sup = DW_FORM_strp_sup,
    strx = DW_FORM_strx,
    strx1 = DW_FORM_strx1,
    strx2 = DW_FORM_strx2,
    strx3 = DW_FORM_strx3,
    strx4 = DW_FORM_strx4,
    udata = DW_FORM_udata,
};

// One DWARF attribute on a DIE: tag (DW_AT_*) + decoded value.
//
// The variant covers everything callers reach for today. Pick the right
// alternative with std::get_if<T>() or std::visit. Forms we don't decode
// (rare ones) come back as std::monostate.
//
//   bool                    DW_FORM_flag, DW_FORM_flag_present
//   uint64_t                addresses (DW_FORM_addr), unsigned constants,
//                           section offsets, DIE references (always given
//                           as a global .debug_info offset so callers can
//                           feed them straight to get_or_create_die)
//   int64_t                 DW_FORM_sdata
//   std::string             every string form (string, strp, strx, ...)
//   std::vector<uint8_t>    DW_FORM_block*, DW_FORM_exprloc
class DwarfAttribute {
   public:
    using Value = std::variant<std::monostate, bool, uint64_t, int64_t, std::string, std::vector<uint8_t>>;

    DwarfAttribute(DwarfAttributeTag tag, DwarfAttributeForm form, Value value)
        : tag(tag), form(form), value(std::move(value)) {}

    DwarfAttributeTag get_tag() const { return tag; }
    DwarfAttributeForm get_form() const { return form; }
    const Value& get_value() const { return value; }

   private:
    DwarfAttributeTag tag;
    DwarfAttributeForm form;
    Value value;
};

}  // namespace ttexalens::native_elf
