# SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
#
# SPDX-License-Identifier: Apache-2.0
"""
Usage:
  parse-debug-bus-json <json-path> [<groups>] [-d <device>] [-l <loc>]

Arguments:
  <json-path>      Path to json file containing debug bus signal groups.
  <groups>         Comma-separated group names or regex patterns to print. [default: all]

Description:
  Loads json file generated by tt-triage containing debug bus signal groups and prints group values for the selected device/location.

Examples:
  parse-debug-bus-json ./debug_bus_signal_groups.json
  parse-debug-bus-json ./debug_bus_signal_groups.json brisc*,rwc_status_signals
  parse-debug-bus-json ./debug_bus_signal_groups.json -d 0 -l 0,0
"""

from __future__ import annotations

import json
import tabulate

from ttexalens import util
from ttexalens.context import Context
from ttexalens.debug_bus_signal_store import SignalGroupSample
from ttexalens.device import Device
from ttexalens.coordinate import OnChipCoordinate
from ttexalens.uistate import UIState
from ttexalens.command_parser import CommandMetadata, tt_docopt, CommonCommandOptions

command_metadata = CommandMetadata(
    short_name="parse",
    long_name="parse-debug-bus-json",
    type="low-level",
    description=__doc__,
    common_option_names=[CommonCommandOptions.Device, CommonCommandOptions.Location],
)


def _parse_groups_arg(groups: dict[str, str], groups_arg: str) -> dict[str, str]:
    groups_arg = groups_arg.strip()
    selected_group_names = set()
    if not groups_arg or groups_arg.lower() == "all":
        selected_group_names = set(groups.keys())
    else:
        for pattern in groups_arg.split(","):
            selected_group_names.update(util.search(list(groups.keys()), pattern.strip()))
    return {name: groups[name] for name in sorted(groups.keys()) if name in selected_group_names}


def print_signal_group(group_name: str, group_sample: SignalGroupSample):
    rows = [[signal_name, value] for signal_name, value in group_sample.items()]
    print(
        tabulate.tabulate(
            rows,
            headers=[group_name, "Values"],
            tablefmt="simple_outline",
            colalign=("left", "left"),
            disable_numparse=True,
        )
    )


def run(cmd_text: str, context: Context, ui_state: UIState):
    dopt = tt_docopt(command_metadata, cmd_text)
    json_path = dopt.args["<json-path>"]
    groups_arg = dopt.args["<groups>"] or "all"

    try:
        with open(json_path, "r", encoding="utf-8") as file:
            data = json.load(file)
    except Exception as e:
        util.ERROR(str(e))
        return []

    device: Device
    for device in dopt.for_each(CommonCommandOptions.Device, context, ui_state):
        device_key = f"Device {device.id}"
        if device_key not in data:
            util.WARN(f"No data found for {device_key}.")
            continue

        loc: OnChipCoordinate
        for loc in dopt.for_each(CommonCommandOptions.Location, context, ui_state, device=device):
            block_type = device.get_block_type(loc) if device.get_block_type(loc) != "functional_workers" else "tensix"
            if block_type not in data[device_key]:
                util.WARN(f"No data found for {block_type} on {device_key}.")
                continue

            loc_key = f"location: {loc.to_user_str()}"
            if loc_key not in data[device_key][block_type]:
                util.WARN(f"No data found for {loc_key} on {device_key}.")
                continue
            loc_data = data[device_key][block_type][loc_key]

            debug_bus_signal_groups = loc_data.get("debug_bus_signal_groups", {})
            if not debug_bus_signal_groups:
                util.WARN(f"No debug_bus_signals found for {device_key} {loc_key}.")
                continue

            selected_groups = _parse_groups_arg(debug_bus_signal_groups, groups_arg)

            if not selected_groups:
                util.WARN(f"No matching groups for {device_key} {loc_key}.")
                continue

            debug_bus = loc.noc_block.debug_bus
            if debug_bus is None:
                util.WARN(f"No debug bus found for {device_key} {loc_key}.")
                continue

            util.INFO(f"Debug bus signals for location {loc.to_user_str()} on device {device.id}")
            for group_name, group_data in selected_groups.items():
                group_sample = SignalGroupSample(int(group_data, 16), debug_bus.signal_groups[group_name])
                print_signal_group(group_name, group_sample)

    return []
