name: "Prepare Wheel Release"
description: "Build ttexalens wheel for release"

inputs:
  python-version:
    description: "Python version to use"
    required: true
  build-version:
    description: "Build version tag (e.g., 'latest', '1.0.0')"
    required: true

outputs:
  wheel-name:
    description: "The name of the wheel artifact"
    value: ${{ steps.set-wheel-name.outputs.wheel-name }}

runs:
  using: "composite"
  steps:
    - name: "Install exalens dependencies"
      uses: ./.github/actions/install-ttexalens-deps
    - name: "Setup Python"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: "Update pip and install dependencies"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip3 install --upgrade build
        pip3 install --upgrade setuptools
        pip3 install wheel
        pip3 install typing-extensions
    - name: "Build wheel"
      shell: bash
      run: |
        make wheel
    - name: "Set wheel name"
      id: set-wheel-name
      shell: bash
      run: |
        echo "wheel-name=tt-exalens-v${{ inputs.build-version }}-${{ inputs.python-version }}" >> $GITHUB_OUTPUT
    - name: "Upload wheel as artifact"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.set-wheel-name.outputs.wheel-name }}
        path: build/ttexalens_wheel/*.whl
