name: "Release"
description: "Release ttexalens wheel, triggered by other workflows. Will create a prerelease."

on:
  workflow_call:
    inputs:
      build-version:
        description: "Version to release (e.g. '1.0.0'), if not provided will be read from VERSION file"
        required: false
        type: string
        default: ""

run-name: "Release by @${{ github.actor }} for ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  prepare-release:
    name: "Prepare Release"
    strategy:
      matrix:
        ubuntu-version: [ "22.04", "24.04" ]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/tenstorrent/tt-exalens/tt-exalens-ird-ubuntu-${{ matrix.ubuntu-version }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Get version"
        id: get-version
        run: |
          if [ -n "${{ inputs.build-version }}" ]; then
            version="${{ inputs.build-version }}"
          else
            version=$(cat VERSION)
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Version is $version"

      - name: "Build and upload wheel artifacts"
        uses: ./.github/actions/prepare-wheel-for-release
        id: prepare-wheel
        with:
          build-version: ${{ steps.get-version.outputs.version }}
          ubuntu-version: ${{ matrix.ubuntu-version }}

  release:
    needs: prepare-release
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - name: "Download wheel artifacts"
        uses: actions/download-artifact@v4

      - name: "List downloaded artifacts"
        run: ls -R

      - name: "Create GitHub Release"
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.prepare-release.outputs.version }}"
          name: Release v${{ needs.prepare-release.outputs.version }}
          prerelease: true
          generate_release_notes: true
          files: |
            */*.whl
