name: "LINTING"

run-name:  Lint TTLENS by @${{ github.actor }} triggered by ${{ github.event_name }} event (${{ github.ref_name }})

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-spdx-licenses:
    runs-on: "ubuntu-22.04"
    name: "Check SPDX licenses"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: infra/requirements-infra.txt
      - name: Install infra deps
        run: python -m pip install -r infra/requirements-infra.txt
      - name: Check SPDX licenses
        run: python -m check_copyright --dry-run --verbose --config infra/copyright-config.yaml .
  format-cpp-files:
    runs-on: "ubuntu-22.04"
    name: "Format cpp files"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -y install clang-format
      - run: |
          scripts/clang-format-repo.sh
          git diff --exit-code
  # format-python-files:
  #   runs-on: "ubuntu-22.04"
  #   name: "Black python files"
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: psf/black@stable
  #       with:
  #         options: "--check"
  #         src: "./ttlens"
  
  