name: "Install Python Dependencies"
description: "Installs Python Dependencies from cache or from PyPI if cache is not available. Uses dbd/requirements.txt and dbd/tests/test_requirements.txt."

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.8"
  dbd-install:
    description: "Whether to install dbd dependencies"
    required: false
    default: ""
  test-install:
    description: "Whether to install test dependencies"
    required: false
    default: ""
  wheel-install:
    description: "Whether to install wheel dependencies"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
        cache-dependency-path: |
          dbd/requirements.txt
          test/test_requirements.txt
    # Install dependencies
    - name: "Install selected dependencies"
      shell: bash
      run: |
        DBD_INSTALL=${{ inputs.dbd-install }} TEST_INSTALL=${{ inputs.test-install }} WHEEL_INSTALL=${{ inputs.wheel-install}} ./scripts/install-deps.sh